### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by hram** [mddanishansari/Phlex#2]
Why so many duplicated lines of code?
For example you can call isFirstRun(SharedPreferences sharedPreferences) from isFirstRun(Context context) and others methods with this bad style

**Comment by mddanishansari** [comment]
The methods with SharedPreference as a parameter is where user can use their own `sp` and wothout those default `SharedPreference` will be used.  

Hope you understand.

**Comment by amorenew** [comment]
```
 public static boolean isAppVersionUpdated(Context context) {
        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context);
        isAppVersionUpdated(context,sharedPreferences)
 }
```
in this sample i removed duplicate code of isAppVersionUpdated method
@mddanishansari @hram

**Comment by mddanishansari** [comment]
Okay. I'll remove all the methods having `SharedPreference` as a parameter and better use app's default `SharedPreference`
